# Generated by Django 5.2.8 on 2025-11-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience_years',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Project Managment', 'Project Managment'), ('1C', '1C'), ('UX/UI', 'UX/UI'), ('Тестировщик', 'Тестировщик')], max_length=100, null=True),
        ),
    ]
