# Generated by Django 5.2.8 on 2025-11-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ведите название книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='загрузите обложку книги')),
                ('annotation', models.TextField(verbose_name='ведите аннотацию книги')),
                ('author', models.CharField(default='Автор неизвестен', max_length=100, verbose_name='укажите автора')),
                ('genre', models.CharField(choices=[('Роман', 'Роман'), ('Повесть', 'Повесть'), ('Рассказ', 'Рассказ'), ('Поэзия', 'Поэзия'), ('Драма', 'Драма'), ('Комедия', 'Комедия'), ('Трагедия', 'Трагедия')], max_length=100, verbose_name='Укажите жанр')),
                ('pages', models.PositiveIntegerField(default=100, verbose_name='укажите количество страницы')),
                ('origin_language', models.CharField(max_length=100, verbose_name='укажите язык книги')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
