# Generated by Django 5.2.8 on 2025-11-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reviews_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='name_user',
        ),
    ]
