# Generated by Django 5.2.8 on 2025-11-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_reviews_name_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
