# Generated by Django 5.2.8 on 2025-11-21 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rat', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='films/')),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Ужасы', 'Ужасы'), ('Мелодрамма', 'Мелодрамма'), ('Боевик', 'Боевик')], max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CineBoard.rating')),
                ('tags', models.ManyToManyField(blank=True, to='CineBoard.tag')),
            ],
        ),
    ]
