# Generated by Django 5.2.8 on 2025-11-16 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0005_alter_reviews_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100, verbose_name='Введите имя:')),
                ('phone', models.CharField(max_length=20, verbose_name='Введите номер телефона:')),
                ('address', models.CharField(max_length=255, verbose_name='Введите ваш адресс:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('новый', 'новый'), ('обработан', 'обработан')], max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
